

scroller= 'HTML'
apend_1= '//*[@id="homefeatured"]/li[ '
apend_2 = ']/div/div[2]/div[1]/span'
product_id = '//ul[@id = "homefeatured"]/li'
highest_price_1 = '//*[@id="homefeatured"]/li[ '
highest_price_2 =']/div/div[2]/h5/a'
cloth_colour = '//*[@id="color_24"]'
cloth_size = '//*[@id="group_1"]'
add_to_cart = '//*[@id="add_to_cart"]/button/span'
proceed_to_checkout = '//*[@id="layer_cart"]/div[1]/div[2]/div[4]/a'
product_quantity = '//*[@id="cart_quantity_up_4_45_0_0"]/span'
dresses_tab = '//div[@id = "block_top_menu"]/ul/li[2]'
# dresses = '//a[@title = "Dresses"]'
dresses = '//*[@id="block_top_menu"]/ul/li[2]/a'
dress_image = '//img[@title = "Printed Summer Dress"]'
dress_click = '//a[@title = "Printed Summer Dress"]'
dress_clr = '//*[@id="color_14"]'
tshirts_tab ='//div[@id="block_top_menu"]/ul/li[3]'
tshirts = '//*[@id="block_top_menu"]/ul/li[3]/a'
shirt = '//*[@id="center_column"]/ul/li/div/div[2]/h5/a'
shirt_image = '//img[@title = "Faded Short Sleeve T-shirts"]'
shirt_click = '//a[@title = "Faded Short Sleeve T-shirts"]'
